steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/api-gitaroom", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/api-gitaroom"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "api-gitaroom",
        "--image",
        "gcr.io/$PROJECT_ID/api-gitaroom",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--port",
        "5000",
        "--timeout",
        "1000s",
        "--allow-unauthenticated",
      ]

options:
  logging: CLOUD_LOGGING_ONLY
