### Create new user 
POST http://localhost:5000/users 
Content-Type: application/json

{
    "name": "Arya", 
    "email": "admin@gmail.com", 
    "gender": "male", 
    "password": "3123", 
    "role": "admin"
}

### Create new course (pakai URL gambar, bukan upload file) 
POST http://localhost:5000/courses 
Content-Type: application/json

{
    "Judul": "Cort AD810",
    "Guru": "lisa",
    "Waktu": 6,
    "harga": 90000,
    "Img": "https://www.enya-music.com/cdn/shop/products/EnyaX4ProCarbonFiberGuitar2.jpg?v=1744796979&width=1445",
    "Deskripsi": "Gitar akustik Cort AD810, body dreadnought klasik dengan harga terjangkau dan kualitas baik.",
    "Kategori": "Gitar Akustik"
}

